blueprint:
  name: Block heat (outdoor-aware + efficient)
  description: >
    Uses an energy-saving policy boolean plus indoor/outdoor temperatures to
    control a heat pump's block/allow behavior with an efficient cold-boost.

    - Energy saving = ON:
      - If warm outside, block heating (virtual temperature).
      - If cold outside, set control temp to 1°C below setpoint to avoid
        direct electric heating.
    - Energy saving = OFF:
      - Compute a cold-boost from outdoor temperature and apply it to the
        heatpump setpoint, with indoor warm-gating and clamping.
  domain: automation

  input:
    section_policy:
      name: "Section — Policy"
      description: " "
      default: "Policy"
      selector:
        text:

    energy_saving_boolean:
      name: Policy — Energy saving boolean (from Energy Saving Policy)
      description: >
        The input_boolean entity managed by the
        [Energy Saving Policy](https://gist.github.com/ohlsont/72e2dc6ffb4d211e74da4f26a89f2e4a)
        blueprint. ON = “save energy now”, OFF = “don’t care”.
      selector:
        entity:
          domain: input_boolean
          multiple: false

    section_sensors:
      name: "Section — Sensors"
      description: " "
      default: "Sensors"
      selector:
        text:

    indoor_temperature_sensor:
      name: Sensors — Indoor temperature sensor (bathroom)
      description: The indoor/bathroom sensor used as the primary reference
      selector:
        entity:
          domain: sensor
          device_class: temperature
          multiple: false

    outdoor_temperature_sensor:
      name: Sensors — Outdoor temperature sensor
      description: Your actual outdoor temperature sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
          multiple: false

    section_control:
      name: "Section — Control"
      description: " "
      default: "Control"
      selector:
        text:

    controll_sensor:
      name: Control — Controllable sensor (MQTT number)
      description: The controllable temperature number your heat pump/Ohmigo reads
      selector:
        entity:
          domain: number
          integration: mqtt
          multiple: false

    heatpump_setpoint:
      name: Control — Heatpump setpoint (°C)
      description: Baseline setpoint that the heatpump is configured for
      default: 20
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    section_energy_saving:
      name: "Section — Energy saving"
      description: " "
      default: "Energy saving"
      selector:
        text:

    virtual_temperature:
      name: Energy saving — Virtual temperature (°C)
      description: Value to write when energy saving = ON and warm outside to block heating
      default: 20
      selector:
        number:
          min: 0
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    energy_saving_warm_shutdown_outdoor:
      name: Energy saving — Warm shutdown threshold (°C)
      description: Above this outdoor temperature, energy saving fully blocks heating
      default: 7
      selector:
        number:
          min: -10
          max: 20
          step: 0.5
          unit_of_measurement: "°C"

    section_cold_boost:
      name: "Section — Cold boost"
      description: " "
      default: "Cold boost"
      selector:
        text:

    cold_threshold:
      name: Cold boost — Threshold (°C)
      description: Outdoor temperature below which cold-boost starts
      default: 0
      selector:
        number:
          min: -30
          max: 10
          step: 0.5
          unit_of_measurement: "°C"

    max_boost:
      name: Cold boost — Max boost (°C)
      description: Maximum boost added to setpoint in cold weather
      default: 3
      selector:
        number:
          min: 0
          max: 8
          step: 0.5
          unit_of_measurement: "°C"

    boost_slope_c:
      name: Cold boost — Slope (°C per 1°C boost)
      description: How many °C colder gives +1°C boost
      default: 5
      selector:
        number:
          min: 1
          max: 12
          step: 1
          unit_of_measurement: "°C"

    warm_margin:
      name: Cold boost — Indoor warm margin (°C)
      description: Suppress cold-boost when indoor temp >= setpoint + margin
      default: 0.3
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
          unit_of_measurement: "°C"

    section_timing:
      name: "Section — Timing"
      description: " "
      default: "Timing"
      selector:
        text:

    refresh_temperature_delay:
      name: Timing — Refresh interval (minutes) when saving = OFF
      description: How often to update the controllable temperature in cheap/don't-care periods
      default: 5
      selector:
        number:
          min: 0
          max: 10
          step: 0.25
          unit_of_measurement: Minutes
          mode: slider

    section_safety:
      name: "Section — Safety"
      description: " "
      default: "Safety"
      selector:
        text:

    min_write_delta:
      name: Safety — Minimum change to write (°C)
      description: Only update if the difference from current value is at least this much
      default: 0.2
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
          unit_of_measurement: "°C"

    section_limits:
      name: "Section — Limits"
      description: " "
      default: "Limits"
      selector:
        text:

    mirror_min_c:
      name: Limits — Control temperature minimum (°C)
      description: Do not set control temperature below this value
      default: -50
      selector:
        number:
          min: -60
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    mirror_max_c:
      name: Limits — Control temperature maximum (°C)
      description: Do not set control temperature above this value
      default: 50
      selector:
        number:
          min: 0
          max: 60
          step: 0.5
          unit_of_measurement: "°C"

mode: restart
max_exceeded: silent

variables:
  es_bool: !input energy_saving_boolean
  indoor_temperature_sensor: !input indoor_temperature_sensor
  outdoor_temperature_sensor: !input outdoor_temperature_sensor
  controll_sensor: !input controll_sensor
  heatpump_setpoint: !input heatpump_setpoint
  virtual_temperature: !input virtual_temperature
  energy_saving_warm_shutdown_outdoor: !input energy_saving_warm_shutdown_outdoor
  cold_threshold: !input cold_threshold
  max_boost: !input max_boost
  boost_slope_c: !input boost_slope_c
  warm_margin: !input warm_margin
  refresh_temperature_delay: !input refresh_temperature_delay
  min_write_delta: !input min_write_delta
  mirror_min_c: !input mirror_min_c
  mirror_max_c: !input mirror_max_c

trigger:
  # React fast to policy changes
  - platform: state
    entity_id: !input energy_saving_boolean

  # Make sure we start in the correct state after restart
  - platform: homeassistant
    event: start

  # Light "tick" to gently correct if something drifts
  - platform: time_pattern
    minutes: "/5"

condition: []

action:
  - choose:

      # --- ENERGY SAVING = ON ---
      - conditions:
          - condition: state
            entity_id: !input energy_saving_boolean
            state: "on"
        sequence:
          - variables:
              outdoor_temp: "{{ states(outdoor_temperature_sensor) | float(default=none) }}"
              cur_ctrl: "{{ states(controll_sensor) | float(default=none) }}"
              setpoint: "{{ heatpump_setpoint | float }}"
              min_c: "{{ mirror_min_c | float(-50) }}"
              max_c: "{{ mirror_max_c | float(50) }}"
              warm_shutdown: "{{ energy_saving_warm_shutdown_outdoor | float }}"
              cold_target: "{{ (setpoint - 1) | float }}"
              target_unclamped: >-
                {% if outdoor_temp is number and outdoor_temp >= warm_shutdown %}
                  {{ virtual_temperature | float }}
                {% else %}
                  {{ cold_target }}
                {% endif %}
              target: "{{ [max_c, [min_c, target_unclamped] | max] | min }}"
              mode_label: >-
                {% if outdoor_temp is number and outdoor_temp >= warm_shutdown %}
                  warm shutdown (virtual block)
                {% else %}
                  cold mode (setpoint-1)
                {% endif %}
          - choose:
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ cur_ctrl is number and target is number and
                         (cur_ctrl - target) | abs >= (min_write_delta | float) }}
                sequence:
                  - service: number.set_value
                    target:
                      entity_id: !input controll_sensor
                    data:
                      value: "{{ target }}"
          - service: logbook.log
            data:
              name: Block Heat
              message: >-
                Energy saving = ON → {{ mode_label }} at {{ target }} °C

      # --- ENERGY SAVING = OFF → COLD-BOOST CONTROL ---
      - conditions:
          - condition: state
            entity_id: !input energy_saving_boolean
            state: "off"
        sequence:
          - alias: Control while energy saving stays OFF
            repeat:
              until:
                - condition: state
                  entity_id: !input energy_saving_boolean
                  state: "on"
              sequence:
                - variables:
                    indoor_temp: "{{ states(indoor_temperature_sensor) | float(default=none) }}"
                    outdoor_temp: "{{ states(outdoor_temperature_sensor) | float(default=none) }}"
                    cur_ctrl: "{{ states(controll_sensor) | float(default=none) }}"
                    setpoint: "{{ heatpump_setpoint | float }}"
                    min_c: "{{ mirror_min_c | float(-50) }}"
                    max_c: "{{ mirror_max_c | float(50) }}"
                    boost_raw: >-
                      {% if outdoor_temp is number and outdoor_temp < (cold_threshold | float) %}
                        {{ ((cold_threshold | float) - outdoor_temp) / (boost_slope_c | float(5)) }}
                      {% else %}
                        0
                      {% endif %}
                    boost_clamped: "{{ [max_boost | float, boost_raw | float] | min }}"
                    boost: >-
                      {% if indoor_temp is number and indoor_temp >= (setpoint + (warm_margin | float)) %}
                        0
                      {% else %}
                        {{ boost_clamped }}
                      {% endif %}
                    target_unclamped: "{{ setpoint + (boost | float) }}"
                    target: "{{ [max_c, [min_c, target_unclamped] | max] | min }}"
                - choose:
                    - conditions:
                        - condition: template
                          value_template: >-
                            {{ target is number and cur_ctrl is number and
                               (target - cur_ctrl) | abs >= (min_write_delta | float) }}
                      sequence:
                        - service: number.set_value
                          target:
                            entity_id: !input controll_sensor
                          data:
                            value: "{{ target }}"
                - delay:
                    minutes: !input refresh_temperature_delay
          - service: logbook.log
            data:
              name: Block Heat
              message: >-
                Energy saving = OFF → cold-boost control every
                {{ refresh_temperature_delay }} min (clamped {{ mirror_min_c }}..{{ mirror_max_c }} °C)

    default: []
