blueprint:
  name: Block heat — target calculator (comfort mode)
  description: >
    Computes the comfort-mode target temperature for Block Heat and writes it to
    an input_number helper.

    Rules:
    - Compute cold boost from outdoor temperature
    - Colder outdoor weather increases control targets by up to max boost
    - If comfort rooms unsatisfied: follow comfort target path
    - If comfort rooms satisfied and storage needs heat: follow storage path
    - If comfort rooms satisfied and storage is fine: use maintenance target
    - Clamp to control min/max before write.
  domain: automation

  input:
    section_sensors:
      name: "Section — Sensors"
      description: " "
      default: "Sensors"
      selector:
        text:

    comfort_room_1_sensor:
      name: Sensors — Comfort room 1 temperature sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
          multiple: false

    comfort_room_2_sensor:
      name: Sensors — Comfort room 2 temperature sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
          multiple: false

    storage_room_sensor:
      name: Sensors — Storage room temperature sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
          multiple: false

    outdoor_temperature_sensor:
      name: Sensors — Outdoor temperature sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
          multiple: false

    section_targets:
      name: "Section — Targets"
      description: " "
      default: "Targets"
      selector:
        text:

    target_comfort_helper:
      name: Targets — Comfort target helper (input_number)
      description: Helper that stores the computed comfort target
      selector:
        entity:
          domain: input_number
          multiple: false

    section_comfort:
      name: "Section — Comfort"
      description: " "
      default: "Comfort"
      selector:
        text:

    comfort_target_c:
      name: Comfort — Target temperature (°C)
      default: 22
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    comfort_to_heatpump_offset_c:
      name: Comfort — Heatpump offset (°C)
      default: 2
      selector:
        number:
          min: 0
          max: 10
          step: 0.5
          unit_of_measurement: "°C"

    storage_target_c:
      name: Comfort — Storage target (°C)
      default: 25
      selector:
        number:
          min: 10
          max: 40
          step: 0.5
          unit_of_measurement: "°C"

    storage_to_heatpump_offset_c:
      name: Comfort — Storage heatpump offset (°C)
      default: 2
      selector:
        number:
          min: 0
          max: 10
          step: 0.5
          unit_of_measurement: "°C"

    maintenance_target_c:
      name: Comfort — Maintenance target (°C)
      default: 20
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    comfort_margin_c:
      name: Comfort — Satisfied margin (°C)
      default: 0.2
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
          unit_of_measurement: "°C"

    section_boost:
      name: "Section — Cold boost"
      description: " "
      default: "Cold boost"
      selector:
        text:

    cold_threshold:
      name: Cold boost — Threshold (°C)
      description: Outdoor temperature below which additive cold boost starts
      default: 0
      selector:
        number:
          min: -30
          max: 15
          step: 0.5
          unit_of_measurement: "°C"

    max_boost:
      name: Cold boost — Max boost (°C)
      description: Maximum boost added to comfort and storage control paths
      default: 3
      selector:
        number:
          min: 0
          max: 10
          step: 0.5
          unit_of_measurement: "°C"

    boost_slope_c:
      name: Cold boost — Slope (°C per +1°C boost)
      description: Outdoor degrees colder required for each +1°C added boost
      default: 5
      selector:
        number:
          min: 1
          max: 15
          step: 1
          unit_of_measurement: "°C"

    section_control:
      name: "Section — Control"
      description: " "
      default: "Control"
      selector:
        text:

    control_min_c:
      name: Control — Minimum control temperature (°C)
      default: 10
      selector:
        number:
          min: 0
          max: 25
          step: 0.5
          unit_of_measurement: "°C"

    control_max_c:
      name: Control — Maximum control temperature (°C)
      default: 26
      selector:
        number:
          min: 5
          max: 40
          step: 0.5
          unit_of_measurement: "°C"

    helper_write_delta_c:
      name: Control — Minimum helper write delta (°C)
      default: 0.05
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          unit_of_measurement: "°C"

mode: restart
max_exceeded: silent

variables:
  comfort_room_1_sensor: !input comfort_room_1_sensor
  comfort_room_2_sensor: !input comfort_room_2_sensor
  storage_room_sensor: !input storage_room_sensor
  outdoor_temperature_sensor: !input outdoor_temperature_sensor
  target_comfort_helper: !input target_comfort_helper
  comfort_target_c: !input comfort_target_c
  comfort_to_heatpump_offset_c: !input comfort_to_heatpump_offset_c
  storage_target_c: !input storage_target_c
  storage_to_heatpump_offset_c: !input storage_to_heatpump_offset_c
  maintenance_target_c: !input maintenance_target_c
  comfort_margin_c: !input comfort_margin_c
  cold_threshold: !input cold_threshold
  max_boost: !input max_boost
  boost_slope_c: !input boost_slope_c
  control_min_c: !input control_min_c
  control_max_c: !input control_max_c
  helper_write_delta_c: !input helper_write_delta_c

trigger:
  - platform: state
    entity_id: !input comfort_room_1_sensor
  - platform: state
    entity_id: !input comfort_room_2_sensor
  - platform: state
    entity_id: !input storage_room_sensor
  - platform: state
    entity_id: !input outdoor_temperature_sensor
  - platform: homeassistant
    event: start
  - platform: time_pattern
    minutes: "/5"

condition: []

action:
  - variables:
      room1_temp: "{{ states(comfort_room_1_sensor) | float(default=none) }}"
      room2_temp: "{{ states(comfort_room_2_sensor) | float(default=none) }}"
      storage_temp: "{{ states(storage_room_sensor) | float(default=none) }}"
      outdoor_temp: "{{ states(outdoor_temperature_sensor) | float(default=none) }}"
      cur_target: "{{ states(target_comfort_helper) | float(default=none) }}"
      comfort_target: "{{ comfort_target_c | float(22) }}"
      comfort_offset: "{{ comfort_to_heatpump_offset_c | float(2) }}"
      storage_target: "{{ storage_target_c | float(25) }}"
      storage_offset: "{{ storage_to_heatpump_offset_c | float(2) }}"
      maintenance_target: "{{ maintenance_target_c | float(20) }}"
      comfort_margin: "{{ comfort_margin_c | float(0.2) }}"
      min_c: "{{ control_min_c | float(10) }}"
      max_c: "{{ control_max_c | float(26) }}"
      comfort_satisfied: >-
        {{ room1_temp is number and room2_temp is number and
           room1_temp >= (comfort_target - comfort_margin) and
           room2_temp >= (comfort_target - comfort_margin) }}
      boost_raw: >-
        {% if outdoor_temp is number and outdoor_temp < (cold_threshold | float(0)) %}
          {{ ((cold_threshold | float(0)) - outdoor_temp) / (boost_slope_c | float(5)) }}
        {% else %}
          0
        {% endif %}
      boost_clamped: "{{ [max_boost | float(3), [0, boost_raw | float] | max] | min }}"
      comfort_target_unclamped: "{{ (comfort_target - comfort_offset) + boost_clamped }}"
      storage_target_unclamped: "{{ (storage_target - storage_offset) + boost_clamped }}"
      storage_needs_heat: >-
        {{ storage_temp is number and storage_temp < (storage_target - comfort_margin) }}
      target_unclamped: >-
        {% if comfort_satisfied and storage_needs_heat %}
          {{ [storage_target_unclamped, comfort_target_unclamped] | max }}
        {% elif comfort_satisfied %}
          {{ maintenance_target }}
        {% else %}
          {{ comfort_target_unclamped }}
        {% endif %}
      target: "{{ [max_c, [min_c, target_unclamped] | max] | min }}"

  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ target is number and
                 (cur_target is not number or
                  (target - cur_target) | abs >= (helper_write_delta_c | float(0.05))) }}
        sequence:
          - service: input_number.set_value
            target:
              entity_id: !input target_comfort_helper
            data:
              value: "{{ target }}"
